- name: Setup K3s on Amazon Linux EC2
  hosts: ec2
  become: yes

  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install K3s with kubeconfig readable
      shell: curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure K3s service is started and enabled
      systemd:
        name: k3s
        state: started
        enabled: yes

    - name: Get latest stable kubectl version
      shell: curl -L -s https://dl.k8s.io/release/stable.txt
      register: kubectl_version
      changed_when: false

    - name: Check if kubectl is already installed
      stat:
        path: /usr/local/bin/kubectl
      register: kubectl_binary

    - name: Download kubectl binary
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version.stdout }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
      when: not kubectl_binary.stat.exists


    - name: Verify kubectl installation
      command: kubectl version --client

    - name: Create .kube directory in home
      file:
        path: /home/ec2-user/.kube
        state: directory
        mode: '0755'
        owner: ec2-user
        group: ec2-user

    - name: Copy kubeconfig file
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ec2-user/.kube/config
        remote_src: yes
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Permanently export KUBECONFIG in .bashrc
      lineinfile:
        path: /home/ec2-user/.bashrc
        line: 'export KUBECONFIG=/home/ec2-user/.kube/config'
        state: present
      become_user: ec2-user

    - name: Verify kubectl can access cluster nodes
      become: false
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config
      command: kubectl get nodes
      register: kubectl_nodes
      ignore_errors: yes

    - name: Show kubectl get nodes output
      debug:
        var: kubectl_nodes.stdout

    - name: Install htop
      yum:
        name: htop
        state: present

