- name: Uninstall K3s from Amazon Linux EC2
  hosts: ec2
  become: yes

  tasks:
    - name: Stop K3s service
      systemd:
        name: k3s
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Remove K3s binary
      file:
        path: /usr/local/bin/k3s
        state: absent

    - name: Remove kubectl binary
      file:
        path: /usr/local/bin/kubectl
        state: absent

    - name: Remove .kube directory from ec2-user
      file:
        path: /home/ec2-user/.kube
        state: absent

    - name: Remove K3s config directory
      file:
        path: /etc/rancher/k3s
        state: absent

    - name: Remove K3s data directory
      file:
        path: /var/lib/rancher/k3s
        state: absent

    - name: Remove K3s log file
      file:
        path: /var/log/k3s.log
        state: absent

    - name: Remove leftover systemd service file
      file:
        path: /etc/systemd/system/k3s.service
        state: absent
      ignore_errors: yes

    - name: Remove additional K3s systemd unit files (if any)
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/systemd/system/k3s-agent.service
        - /etc/systemd/system/k3s.service.env
      ignore_errors: yes

    - name: Reload systemd daemon
      command: systemctl daemon-reload
      ignore_errors: yes

    - name: Remove KUBECONFIG export from .bashrc
      lineinfile:
        path: /home/ec2-user/.bashrc
        regexp: '^export KUBECONFIG='
        state: absent
      become_user: ec2-user
      ignore_errors: yes
